# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=50)),
                ('oauth_secret', models.CharField(max_length=50)),
            ],
        ),
    ]
